### ISSUE TITLE
Can't `npm start` React App because of missing dependency regex.js

### ISSUE THREAD

**Issue by Iipal** [ajv-validator/ajv-keywords#189]
Just as the title said :(

# error output:
```
$ npm start

> app@0.1.0 start
> react-scripts start

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module './regexp'
Require stack:
- /path/to/app/node_modules/ajv-keywords/keywords/index.js
- /path/to/app/node_modules/ajv-keywords/index.js
- /path/to/app/node_modules/webpack/node_modules/schema-utils/src/validateOptions.js
- /path/to/app/node_modules/webpack/node_modules/schema-utils/src/index.js
- /path/to/app/node_modules/webpack/lib/SourceMapDevToolPlugin.js
- /path/to/app/node_modules/webpack/lib/WebpackOptionsApply.js
- /path/to/app/node_modules/webpack/lib/webpack.js
- /path/to/app/node_modules/react-scripts/scripts/start.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/path/to/app/node_modules/ajv-keywords/keywords/index.js:6:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/path/to/app/node_modules/ajv-keywords/keywords/index.js',
    '/path/to/app/node_modules/ajv-keywords/index.js',
    '/path/to/app/node_modules/webpack/node_modules/schema-utils/src/validateOptions.js',
    '/path/to/app/node_modules/webpack/node_modules/schema-utils/src/index.js',
    '/path/to/app/node_modules/webpack/lib/SourceMapDevToolPlugin.js',
    '/path/to/app/node_modules/webpack/lib/WebpackOptionsApply.js',
    '/path/to/app/node_modules/webpack/lib/webpack.js',
    '/path/to/app/node_modules/react-scripts/scripts/start.js'
  ]
}

```

***

# package.json:
```json
{
  "name": "app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@date-io/moment": "^1.3.13",
    "@material-ui/core": "^4.11.3",
    "@material-ui/lab": "^4.0.0-alpha.57",
    "@material-ui/pickers": "^3.3.10",
    "@types/node": "^12.19.15",
    "@types/react": "^16.14.3",
    "@types/react-dom": "^16.9.10",
    "axios": "^0.21.1",
    "core-js": "3.3",
    "moment": "^2.29.1",
    "qs": "^6.5.2",
    "qs-stringify": "^1.2.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-redux": "^7.2.2",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^4.0.1",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.8",
    "redux-thunk": "^2.3.0",
    "typescript": "^4.1.3",
    "uuidv4": "^6.2.6",
    "web-vitals": "^0.2.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "lint": "eslint --ext .ts,.tsx src --color",
    "format": "prettier --write src/**/*.{ts,tsx}",
    "isready": "npm run format && npm run lint"
  },
  "eslintConfig": {
    "extends": [
      "react-app"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@ckeditor/ckeditor5-build-classic": "^27.0.0",
    "@ckeditor/ckeditor5-react": "^3.0.2",
    "@types/react-redux": "^7.1.16",
    "@types/react-router-dom": "^5.1.7",
    "@typescript-eslint/eslint-plugin": "^4.14.2",
    "@typescript-eslint/parser": "^4.14.2",
    "eslint": "^7.19.0",
    "eslint-config-prettier": "^7.2.0",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-react": "^7.22.0",
    "prettier": "^2.2.1"
  }
}
```

**Comment by Iipal** [comment]
there is no `regex.js` at all
![image](https://user-images.githubusercontent.com/31858171/121817185-78d86c00-cc88-11eb-838b-414337f2ddb2.png)

**Comment by epoberezkin** [comment]
I think it should be addressed via react app configuration, closing it here, as it is not the package issue.
